# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib smoothbp, .registration = TRUE
NULL

# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_smoothbp_wrappers", use_symbols = TRUE, package_name = "smoothbp")

#' @usage NULL
#' @useDynLib smoothbp, .registration = TRUE
NULL

#' Run Metropolis-within-Gibbs sampler for the smooth change-point model.
#'
#' @param y           Response vector (n).
#' @param tau         Time variable (n).
#' @param x_b0        Design matrix for b0 as flat column-major vector.
#' @param p_b0        Number of columns in x_b0.
#' @param x_b1        Design matrix for b1.
#' @param p_b1        Number of columns in x_b1.
#' @param x_b2        Design matrix for b2.
#' @param p_b2        Number of columns in x_b2.
#' @param x_om        Design matrix for omega.
#' @param p_om        Number of columns in x_om.
#' @param x_rho       Design matrix for rho.
#' @param p_rho       Number of columns in x_rho.
#' @param group_b0    0-based group indices for b0 random intercept (-1 = no RE).
#' @param n_groups_b0 Number of RE groups (0 = no random effect).
#' @param prior_mean  Prior means concatenated [b0 | b1 | b2 | omega | rho].
#' @param prior_sd    Prior SDs (same order).
#' @param prior_lb    Lower bounds (-Inf for unconstrained).
#' @param prior_ub    Upper bounds (+Inf for unconstrained).
#' @param sigma_shape Shape of InvGamma prior on residual variance.
#' @param sigma_scale Scale of InvGamma prior on residual variance.
#' @param sigma_u_shape Shape of InvGamma prior on RE variance.
#' @param sigma_u_scale Scale of InvGamma prior on RE variance.
#' @param step_om     Initial MH step size for omega coefficients.
#' @param step_rho    Initial MH step size for rho coefficients.
#' @param chains      Number of independent chains.
#' @param iter        Total iterations per chain (warmup + sampling).
#' @param warmup      Number of warmup iterations discarded.
#' @param seed        Integer random seed.
#' @param verbose     Print progress to the R console.
#' @param n_cores     Number of threads for parallel chain execution.
#'                    1 = sequential (with progress bar); > 1 = parallel
#'                    (progress bar suppressed; chains run concurrently).
#' @return List with one matrix per chain (rows = post-warmup draws, cols = parameters).
#' @export
run_mcmc <- function(y, tau, x_b0, p_b0, x_b1, p_b1, x_b2, p_b2, x_om, p_om, x_rho, p_rho, group_b0, n_groups_b0, prior_mean, prior_sd, prior_lb, prior_ub, sigma_shape, sigma_scale, sigma_u_shape, sigma_u_scale, step_om, step_rho, chains, iter, warmup, seed, verbose, n_cores) .Call(wrap__run_mcmc, y, tau, x_b0, p_b0, x_b1, p_b1, x_b2, p_b2, x_om, p_om, x_rho, p_rho, group_b0, n_groups_b0, prior_mean, prior_sd, prior_lb, prior_ub, sigma_shape, sigma_scale, sigma_u_shape, sigma_u_scale, step_om, step_rho, chains, iter, warmup, seed, verbose, n_cores)

# nolint end
